### ISSUE TITLE
Client Error

### ISSUE THREAD

**Issue by bridges-wood** [bridges-wood/volatil-core#1]
When a client tries to connect to a server that is not online, the application fails with a NullPointerException.

# Tasks
- [ ] Find out why the exception occurs.
- [ ] Fix the problem.
- [ ] Update dependent repositories.
